services:
  frontend:
    build:
      context: src
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

  reverse-proxy:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./dev/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      frontend:
        condition: service_started

volumes:
  db-data:
